services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5434:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - NODE_ENV=staging
      - Database__url=postgres://user:password@db:5432/db
      - App__ENV=development
      - App__port=3000
      - App__host="localhost"
      - App__prefix="/api"
      - CORS__origin="*"
      - CORS__methods="GET,HEAD,PUT,PATCH,POST,DELETE"
      - CORS__preflightContinue=false
      - CORS__optionsSuccessStatus=204
      - Swagger__json="/docs/openapi.json"
      - Swagger__url="/api/docs"
    links:
      - db:db